---
# tasks file for apigee-opdk-setup-os-pip
- block:
  - name: Update pip
    pip:
      name: pip
      state: latest
    register: result

  rescue:

    - block:
      - name: Install pip
        yum: python-pip
        state: latest

      rescue:
        - name: Install epel
          import_role:
            name: apigee-opdk-setup-os-epel

        - name: Install pip
          yum:
            name: python-pip
            state: latest

  become: yes

- name: Update python packages
  tags: ['pip']
  become: yes
  pip:
    name: '{{ item }}'
    state: present
  with_items: "{{ pip_packages }}"

#  rescue:
#    - name: Download pip package manager
#      become: yes
#      tags: ['pip-manager']
#      get_url:
#        url: https://bootstrap.pypa.io/get-pip.py
#        dest: /tmp/get-pip.py
#      when: pip_conf_dir is not defined
#
#    - name: Install pip package manager
#      become: yes
#      tags: ['pip-manager']
#      shell: python /tmp/get-pip.py
#      when: pip_conf_dir is not defined
#
#    - name: Update pip
#      tags: ['pip']
#      become: yes
#      pip:
#        name: pip
#        state: latest
#
#    - name: Update python packages
#      tags: ['pip']
#      become: yes
#      pip:
#        name: '{{ item }}'
#        state: present
#      with_items: "{{ pip_packages }}"
